version: "3.9"
services:
  app:
    build: "."
    container_name: soha-test
    restart: "no"        
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    expose:
      - 5173
networks:
  default:
    name: soha
